---               #application installation playbook
- name: install and start the service
  hosts: localhost

  tasks:
  - name: installaling nginx
    yum:            #yum is a module
      name: nginx
      state: present
  - name: starting the nginx service
    service: 
      name: nginx
      state: started
      enabled: true
